### PR TITLE
Create leagueauth.js

### PR DESCRIPTION
**Pull request by ashyudhajit**
Room league auth lol...

### CODE REVIEW

**Comment by panpawn** [comment]
We have roomauth, no need to over-complicate this...

**Comment by ashyudhajit** [comment]
This is/leagueauth
And iam not copying codes . This command is essential for leagues of the server

**Comment by panpawn** [comment]
I don't think I would call this 'essential'.

**Comment by ashyudhajit** [comment]
Ok nvm....

**Pull request closed without merging**
