### PR TITLE
Refactor economy.readMoney()

### PR DESCRIPTION
**Pull request by SilverTactic**

### CODE REVIEW

**Comment by panpawn** [comment]
Have you tested this, @SilverTactic ?

Does this give any performance improvements or is this just a general clean up?

**Comment by panpawn** [comment]
Also, this commit name should probably say ``Refactor economy.readMoney()`` to be more specific imo

**Comment by SilverTactic** [comment]
Ye, I've tested it. You could test it too.

**Comment by panpawn** [comment]
Merge conflicts r no fun huh...

This has been changed to follow ES6 styling since in our new economy plugin anyways, so closing this.

**Pull request closed without merging**
