### PR TITLE
Added Panagrams.

### PR DESCRIPTION
**Pull request by SilverTactic**
Just a game where a jumbled pokemon name is given and you have to guess it. =P

### CODE REVIEW

**Comment by panpawn** [comment]
I like it with the bot as it is honestly, it allows us to easily toggle things like what rank people have to be to use it as well as one to set the time for the next session.  I'll reference this later if I decided to make it server sided, though!

Thanks!

**Comment by SilverTactic** [comment]
Alright, sure. =)

**Comment by panpawn** [comment]
https://github.com/panpawn/Pokemon-Showdown/commit/5319801b7db92c2fcc2f53e97442ea516c6f746e

**Comment by panpawn** [comment]
The newest version of our script can be found here: https://github.com/panpawn/Pokemon-Showdown/blob/master/chat-plugins/panagrams-beta.js

**Comment by SilverTactic** [comment]
Oo, I see. That's cool.
Btw, mind if I make a few edits?

**Comment by panpawn** [comment]
You can make another pull request if you want, sure :o: 
1. This allows for there to be automated games instead of manually doing the command for each game to start every time.
2. It's necessary for when there aren't people who are good at it playing and not many staff are around to restart them.

**Comment by panpawn** [comment]
@SilverTactic

**Comment by SilverTactic** [comment]
Yeah, I'm here now (Sorry for not replying earlier >.<)

**Comment by SilverTactic** [comment]
I guess the new changes are fine. I'm actually creating a new script (a little bit neater one), and I might create a feature that saves one's panagram records too. I'll add all your features too. What do you think?

**Comment by panpawn** [comment]
That sounds interesting.  How will it save a users progress?  A csv file?  Or an sqlite3 database? Or do you have something else in mind?

**Comment by SilverTactic** [comment]
I actually planned on using a JSON file, @panpawn.

**Comment by panpawn** [comment]
Closing this PR since it's now outdated.  Feel free to make a new one when / if you wish, @SilverTactic.

**Comment by panpawn** [comment]
@SilverTactic - did you use a end up using a JSON file for these? o.o?

**Comment by SilverTactic** [comment]
@panpawn Nah, not really. I kinda stopped working on editing panagrams because I was more interested in other stuff

**Comment by panpawn** [comment]
@SilverTactic - what other games have you made? :o

**Comment by SilverTactic** [comment]
@panpawn I made tic tac toe, poof commands, and a few other scripts for the server I help code for
I have hangman, roulette and dice too, but I made those a while back xD

**Comment by panpawn** [comment]
Link me to your roulette one :o

**Comment by panpawn** [comment]
@SilverTactic

**Comment by SilverTactic** [comment]
Sure @panpawn 
https://github.com/Sora-League/Sora/blob/master/custom/Games/roulette.js
You'll need to edit it, though. It uses our server's currency system.

**Pull request closed without merging**
