### PR TITLE
remove unneeded css and spank commands.

### PR DESCRIPTION
**Pull request by NotBlizzard**

### CODE REVIEW

**Comment by panpawn** [comment]
Spank command is still used, CSS is planning on getting completely revamped soon enough, and I'd like to keep the old room commands in case I want to move back to that system eventually.

**Comment by NotBlizzard** [comment]
version control is a thing.

**Comment by panpawn** [comment]
@NotBlizzard - saving old code that could be useful in the near future is not a problem.

Please re read my posts before reposting.

**Comment by panpawn** [comment]
Also, the CSS command gets used very often for people asking questions about our CSS.

PRs are for suggestions and not blatant insults.  You have been banned from making PRs to this respiratory as a result.

**Pull request closed without merging**
