### PR TITLE
Introduce user statuses

### PR DESCRIPTION
**Pull request by panpawn**
This creates commands users can use to set their status that will be shown in their profile.

### CODE REVIEW

**Comment by panpawn** [comment]
Thoughts?

**Comment by SilverTactic** [comment]
Not bad, but tbh, how many of us even USE /profile?

**Comment by SilverTactic** [comment]
OH, I KNOW
Why not make statuses a part of both /whois AND /profile? That way, more people would see it

**Comment by panpawn** [comment]
Do many people really use /whois, though?

**Comment by SilverTactic** [comment]
Not sure if <em>many</em> people use it, but I'm pree sure a lot more people use /whois than /profile
It doesn't hurt to include statuses in both of them, right?

**Comment by panpawn** [comment]
I think the friendslist, profile, and statuses should all be joined into one system.

I'm just not sure how to do it where it looks good.

**Comment by panpawn** [comment]
Closing for now, will reopen later if I want to merge.

**Pull request closed without merging**
