### PR TITLE
Fix avatar display in /profile

### PR DESCRIPTION
**Pull request by SilverTactic**
Shoutout to Darkero for finding out this error
If you don't understand the <code>if (targetUser.avatar[0] === '#')</code> statement, it basically checks whether a user's using a temporary avatar (and if so, their avatar would start with a #). (Using <code>/avatar #zinnia</code> is how you can set a temporary Zinnia avatar)

### CODE REVIEW

**Comment by panpawn** [comment]
This doesn't meet any of our styling specifications and there's no way that would pass ``npm test``

**Comment by panpawn** [comment]
Done in https://github.com/panpawn/Pokemon-Showdown/commit/d31e496db66c1e56239d412d97425bd58c1aaece

**Comment by SilverTactic** [comment]
Well it's less confusing than nesting conditional operators lol

**Comment by panpawn** [comment]
True

**Pull request closed without merging**
